import {
    AudioWaveform,
    BookOpen,
    Bot,
    Command,
    Frame,
    GalleryVerticalEnd,
    PieChart,
    Settings2,
    SquareTerminal,
    MapPinned,
    Activity,
    Box,
    TagIcon,
    Building2,
    Factory,
    Handshake,
    UserLock,
    Hash,
    FileBox,
    Shield,
    ShieldUser,
    Paperclip,
    Bug,
    Users,
    ShieldHalf,
} from 'lucide-react'

const iconMap: Record<string, React.ElementType> = {
    activity: Activity,
    box: Box,
    tag: TagIcon,
    building2: Building2,
    hash: Hash,
    userlock: UserLock,
    filebox: FileBox,
    handshake: Handshake,
    audio: AudioWaveform,
    book: BookOpen,
    bot: Bot,
    command: Command,
    frame: Frame,
    gallery: GalleryVerticalEnd,
    map: MapPinned,
    pie: PieChart,
    settings: Settings2,
    terminal: SquareTerminal,
    factory: Factory,
    shield: Shield,
    shielduser: ShieldUser,
    paperclip: Paperclip,
    bug: Bug,
    users: Users,
    shieldhalf: ShieldHalf,
}

export function getIconByName(name: string): React.ElementType | null {
    return iconMap[name] || null
}
